// GENERATED by scripts/build-tokens.mjs from tokens/m3.tokens.json — do not edit by hand.

export const themeIds = [
  "baseline-light",
  "baseline-light-hc",
  "baseline-light-mc",
  "baseline-dark",
  "baseline-dark-hc",
  "baseline-dark-mc",
  "monochrome-light",
  "monochrome-dark",
  "pink-light",
  "pink-dark",
  "rose-light",
  "rose-dark",
  "red-light",
  "red-dark",
  "orange-light",
  "orange-dark",
  "yellow-light",
  "yellow-dark",
  "chartreuse-light",
  "chartreuse-dark",
  "green-light",
  "green-dark",
  "teal-light",
  "teal-dark",
  "cyan-light",
  "cyan-dark",
  "blue-light",
  "blue-dark",
  "indigo-light",
  "indigo-dark",
  "purple-light",
  "purple-dark"
] as const

export type ThemeId = (typeof themeIds)[number]
