// Generates src/styles/tokens.css and src/theme/themes.gen.ts from tokens/m3.tokens.json.
// The JSON is the single source of truth, exported from the Figma M3 Design Kit.
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const tokens = JSON.parse(readFileSync(resolve(root, 'tokens/m3.tokens.json'), 'utf8'))

const roles = tokens.colorRoles.split(' ')

// Figma mode name -> theme id used in data-m3-theme="…"
function themeId(mode) {
  const baseline = {
    Light: 'baseline-light',
    'Light Medium Contrast': 'baseline-light-mc',
    'Light High Contrast': 'baseline-light-hc',
    Dark: 'baseline-dark',
    'Dark Medium Contrast': 'baseline-dark-mc',
    'Dark High Contrast': 'baseline-dark-hc',
  }
  if (baseline[mode]) return baseline[mode]
  const [palette, scheme] = mode.split(' ')
  return `${palette.toLowerCase()}-${scheme === 'DT' ? 'dark' : 'light'}`
}

const themes = Object.entries(tokens.colorModes).map(([mode, row]) => {
  const values = row.split(' ')
  if (values.length !== roles.length) throw new Error(`${mode}: expected ${roles.length} colors, got ${values.length}`)
  const id = themeId(mode)
  return { id, mode, dark: id.includes('-dark'), values }
})

const colorBlock = (t) => roles.map((r, i) => `  --md-sys-color-${r}: #${t.values[i]};`).join('\n')

const fontVar = (f) => `var(--md-ref-typeface-${f})`
const weightVar = (w) => `var(--md-ref-typeface-weight-${w})`

const typeVars = Object.entries(tokens.typescale)
  .map(([name, s]) =>
    [
      `  --md-sys-typescale-${name}-font: ${fontVar(s.font)};`,
      `  --md-sys-typescale-${name}-size: ${s.size / 16}rem;`,
      `  --md-sys-typescale-${name}-line-height: ${s.lineHeight / 16}rem;`,
      `  --md-sys-typescale-${name}-tracking: ${s.tracking / 16}rem;`,
      `  --md-sys-typescale-${name}-weight: ${weightVar(s.weight)};`,
      `  --md-sys-typescale-${name}-weight-emphasized: ${weightVar(s.emphasized)};`,
    ].join('\n'),
  )
  .join('\n')

const typeClasses = Object.keys(tokens.typescale)
  .map((name) => {
    const v = (p) => `var(--md-sys-typescale-${name}-${p})`
    const body = `  font-family: ${v('font')};\n  font-size: ${v('size')};\n  line-height: ${v('line-height')};\n  letter-spacing: ${v('tracking')};`
    return `.md-typescale-${name} {\n${body}\n  font-weight: ${v('weight')};\n}\n.md-typescale-${name}-emphasized {\n${body}\n  font-weight: ${v('weight-emphasized')};\n}`
  })
  .join('\n')

const shapeVars = Object.entries(tokens.shape)
  .map(([k, v]) => `  --md-sys-shape-corner-${k}: ${k === 'full' ? '9999px' : `${v}px`};`)
  .join('\n')

const elevationVars = (list) => list.map((s, i) => `  --md-sys-elevation-level${i + 1}: ${s};`).join('\n')

const light = themes.find((t) => t.id === 'baseline-light')

const css = `/* GENERATED by scripts/build-tokens.mjs from tokens/m3.tokens.json — do not edit by hand. */

:root {
  --md-ref-typeface-brand: '${tokens.font.brand}', system-ui, sans-serif;
  --md-ref-typeface-plain: '${tokens.font.plain}', system-ui, sans-serif;
  --md-ref-typeface-weight-regular: ${tokens.font.weight.regular};
  --md-ref-typeface-weight-medium: ${tokens.font.weight.medium};
  --md-ref-typeface-weight-bold: ${tokens.font.weight.bold};

${typeVars}

${shapeVars}

  --md-sys-elevation-level0: none;
${elevationVars(tokens.elevation.light)}

  --md-sys-state-hover-opacity: ${tokens.stateLayerOpacity.hover};
  --md-sys-state-focus-opacity: ${tokens.stateLayerOpacity.focus};
  --md-sys-state-pressed-opacity: ${tokens.stateLayerOpacity.pressed};
  --md-sys-state-dragged-opacity: ${tokens.stateLayerOpacity.dragged};

${colorBlock(light)}
  color-scheme: light;
}

${themes
  .map(
    (t) =>
      `/* ${t.mode} */\n[data-m3-theme='${t.id}'] {\n${colorBlock(t)}\n  color-scheme: ${t.dark ? 'dark' : 'light'};${t.dark ? `\n${elevationVars(tokens.elevation.dark)}` : ''}\n}`,
  )
  .join('\n\n')}

${typeClasses}
`

const ts = `// GENERATED by scripts/build-tokens.mjs from tokens/m3.tokens.json — do not edit by hand.

export const themeIds = ${JSON.stringify(themes.map((t) => t.id), null, 2)} as const

export type ThemeId = (typeof themeIds)[number]
`

writeFileSync(resolve(root, 'src/styles/tokens.css'), css)
writeFileSync(resolve(root, 'src/theme/themes.gen.ts'), ts)
console.log(`tokens: ${themes.length} color themes × ${roles.length} roles, ${Object.keys(tokens.typescale).length} type roles`)
